### ISSUE TITLE
Some articles have very small font size

### ISSUE THREAD

**Issue by Trim** [Alkarex/EasyRSS#17]
Hello,

Sometimes, it's hard to read some articles, because easyrss seems to force the display of the text to fit exactly the screen width.

The issue appears often when an article contains a very long URL, like on this page:
![easyrss_screenshot](https://cloud.githubusercontent.com/assets/307130/13554502/b1be1b64-e3a9-11e5-8419-b61d9ee359d5.jpg)

Is it possible to apply CSS properties before displaying the articles ?
If yes, it could be interesting to use the hint given in [this French speaking (sorry) article](http://lokoyote.eu/css-encore-quelques-effets-avances-lehollandaisvolant/).

The idea is to ask the browser to display ellipsis when text is too large for the screen, with this CSS rule:

```css
.content a {
   display: inline-block; /* Needed to be able to apply ellipsis method */
   overflow: hidden;
   white-space: nowrap;
   text-overflow: ellipsis;
   vertical-align: bottom;
   max-width: 100%; /* Needed to rule that the text block can't be bigger than the parent container */
}
```

Do you think it is doable ?

It seems this issue come also when there's `<pre>` blocks:
![easyrss_screenshot_codeblock](https://cloud.githubusercontent.com/assets/307130/13554551/f4c7e95c-e3aa-11e5-89c9-040817907af4.jpg)

Here I think we can't use this solution, because we'll loose some important information. What do you think ?

Best regards,
Trim

PS: For issue with urls, I think it happens often with this RSS feed: https://linuxfr.org/tags/agenda_du_libre/public.atom

For issue with `<pre>` it could happen often with this one (depending on the content of user requests): https://linuxfr.org/forums/programmation-c--2.atom
